import pytest
from pathlib import Path
import os
import functools, inspect


def cmdrun_test(test_func):
    """Decorator to generate images for the userguide mdbook from
    a test. For simplicity and ease of use, when using this decorator,
    ensure only one image is generated by the test function, and that it
    has the same name as the function itself."""
    # capture the original signature
    sig = inspect.signature(test_func)

    @functools.wraps(test_func)
    def wrapper(*args, **kwargs):
        # run the real test, letting pytest supply fixtures
        result = test_func(*args, **kwargs)

        # after-test hook: if the test returned None, assume pass
        if result is None:
            # try to locate the image we know the test wrote:
            # we expect the test to take an `image_dir` fixture
            image_dir = kwargs.get("image_dir")
            if image_dir is None and len(args) > 0:
                # pytest will pass fixtures positionally if you prefer;
                # image_dir is the first arg in your test signature
                image_dir = args[0]

            # build up an expected filename: test_name.png
            image_path = None
            if image_dir:
                candidate = image_dir / f"{test_func.__name__}.png"
                if candidate.exists():
                    image_path = candidate

            if image_path:
                print(f"![{test_func.__name__}]({image_path})")
            else:
                print("Test passed, but no image generated.")
        else:
            print("Test failed.")

        return result

    # **crucial**: give the wrapper the same signature as the original
    wrapper.__signature__ = sig
    return wrapper


@pytest.fixture
def temp_data_dir(tmp_path) -> Path:
    """
    Creates an isolated temp directory for each test and returns it.
    """
    # tmp_path is a fresh Path for *this* test
    d = tmp_path / "data"
    d.mkdir()
    return d


# @pytest.fixture
# def temp_file(temp_data_dir) -> Path:
#     """
#     Creates a single file "input.txt" in the temp_data_dir
#     and returns its Path.
#     """
#     f = temp_data_dir / "input.txt"
#     f.write_text("default contents\n")
#     return f


@pytest.fixture
def image_dir() -> Path:
    # __file__ is tests/conftest.py
    return Path(__file__).parent.parent / "docs/userguide/src/images"
